project:
  type: website

website:
  title: "My Quarto Website"
  navbar:
    left:
      - text: "Home"
        href: home.qmd
      - text: "About"
        href: about.qmd
      - text: "Assignments"
        menu:
          - text: "Assignment 1"
            href: Assignment 1.qmd
            
       

